

                term  ::=  "𝘪𝘥_"<NO_WHITESPACE>argument

                        |  ( "𝘥𝘰𝘮𝘢𝘪𝘯" | "𝘤𝘰𝘥𝘰𝘮𝘢𝘪𝘯" )<NO_WHITESPACE>"(" argument ")"

                        |  argument ( ( ";" argument )                  (1)

                                    | ( <NO_WHITESPACE>"⁻¹" )           (2) ) 

                        ;

