

                term  ::=  "id_"<NO_WHITESPACE>argument

                        |  ( "domain" | "codomain" )<NO_WHITESPACE>"(" argument ")"

                        |  argument ( ( ":" argument "⟶" argument )     (1)

                                    | ( ";" argument )                  (2)

                                    | ( <NO_WHITESPACE>"⁻¹" )           (3) ) 

                        ;

